### ISSUE TITLE
Feature Request: Generate and visualize types of bundle categories

### ISSUE THREAD

**Issue by ErikKoppenhagen** [OpenKieler/osgiviz#12]
A boundle may have multiple boundle categories. These categories might have different contexts, e.g. one category defines its architectural layer, the other one its business context.
These contexts (or types) of boundle categories could be defined by using a colon:

Bundle Name | Bundle Category (MANIFEST.MF)
-- | --
Bundle 1 | Layer:view,Subject:menubar
Bundle 2 | Layer:controller
Bundle 3 | Subject:dialogs
Bundle 4 | storage

Because it wouldn't make sense to have them all shown in the same bundle category view, each type requires their on view. For the given data this could be as following:
![bundle_types](https://user-images.githubusercontent.com/60260431/73075907-4a07fd00-3ebd-11ea-84ea-1881abf3b060.png)

This is linked to issues [7](https://github.com/OpenKieler/osgiviz/issues/7), [8](https://github.com/OpenKieler/osgiviz/issues/8) and [11](https://github.com/OpenKieler/osgiviz/issues/11)

**Comment by NiklasRentzCAU** [comment]
As this is not standardized in OSGi and therefore not used in many example OSGi projects, this seems to be a very specific use case that requires the projects to follow this hierarchical bundle category naming scheme just to use a feature like this.
Default suggestions for bundle category names are listed by the OSGi alliance [here](https://www.osgi.org/developer/specifications/reference/) and don't suggest this to be a feature.
Closed and won't do.
