### ISSUE TITLE
Issue: Tooltips of the action bar

### ISSUE THREAD

**Issue by ErikKoppenhagen** [OpenKieler/osgiviz#16]
The tooltips of the action bar on the right just repeat the label of the action - they have no additional value. Please make them more specific and explaining (or remove them at all?).

**Comment by NiklasRentzCAU** [comment]
The tooltips of the actions in the sidebar do have a description tooltip different from the action name already, the options below that however have that issue. KLighD also has this as an issue [here](https://rtsys.informatik.uni-kiel.de/jira/projects/KIPRA/issues/KIPRA-1891).
Closing as duplicate.
