### ISSUE TITLE
Feature Request. Copy & paste

### ISSUE THREAD

**Issue by ErikKoppenhagen** [OpenKieler/osgiviz#18]
At the current point of time, I can't copy something from the diagram view.

**Comment by NiklasRentzCAU** [comment]
What do you want to copy? Diagram elements themselves or just texts? For diagram elements I would not quite what you mean, for texts this currently is just not possible, please file an issue over [here](https://rtsys.informatik.uni-kiel.de/jira/projects/KIPRA/issues) as this is KLighD functionality.

**Comment by ErikKoppenhagen** [comment]
Created [issue](https://rtsys.informatik.uni-kiel.de/jira/browse/KIPRA-2033)
