### ISSUE TITLE
Feature Request: Missing description texts and highlighting

### ISSUE THREAD

**Issue by ErikKoppenhagen** [OpenKieler/osgiviz#5]
Unfortunatly some bundles/features/... may miss a description and an _about.html_, but the label "Description:" is still shown. Additionally, there is no different style of the name and the description of an element except the vertical line.

So I have two suggestions:
1. If there is no description, remove the "_Description:_" label from the element.
2. Either the name of the element could be written **bold** or the description could be written _italic_ or in a smaller font.

**Comment by NiklasRentzCAU** [comment]
Good suggestions, I implemented omitting the description texts if they are empty and some bold headlines for expanded elements and overviews.
